### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()

### ISSUE THREAD

**Issue by bihor** [colorcube/content_overview#2]
I have just testet the version 0.3.0 with TYPO3 10.4.9, but I get this error message:

 Error

Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()
in /xyz/typo3conf/ext/content_overview/Classes/Controller/ContentOverviewController.php line 491

**Comment by colorcube** [comment]
I guess your installation is not based on composer?

**Comment by bihor** [comment]
Yes, you are right.

**Comment by georgringer** [comment]
@colorcube this is not related to composer or not composer but to `doctrine/dbal:^2.11`. I suggest to change the code as proposed in the PR

**Comment by colorcube** [comment]
Yes you're right. But with composer it seems you get newer doctrine packages where error does not occur. That's why I asked.
